services:
    Creonit\PageBundle\Admin\PageModule:
        tags:
            - { name: creonit_admin.module }

    Creonit\PageBundle\Routing\PageLoader:
        arguments: ['%creonit_page.controller%', '%creonit_page.ignore_route%', '%creonit_page.ignore_path%']
        tags:
            - { name: routing.loader }

    Creonit\PageBundle\Service\HostResolver:
        public: true
        autowire: true

    Creonit\PageBundle\Service\PageHostService:
        public: true
        arguments:
            - '@router'

    Creonit\PageBundle\Service\PageService:
        public: true
        arguments:
            - '@router'
            - '%kernel.cache_dir%'
            - '%creonit_page.ignore_route%'
            - '%creonit_page.ignore_path%'

    creonit_page:
        alias: Creonit\PageBundle\Service\PageService
        public: true